### ISSUE TITLE
Game crashes on 1.19.4

### ISSUE THREAD

**Issue by Scarlaid** [70CentsApple/modify-camera-collision#1]
Freelook mods seem to be having incompatibility, or only [Perspektive](https://modrinth.com/mod/perspektive)

Running MCC and Perspektive together give you a crash whenever you try to go into Third Person Freecam (Freelook)

**Comment by 70CentsApple** [comment]
Could not reproduce, tested on 1.20.1

https://github.com/70CentsApple/modify-camera-collision/assets/63957117/caa91573-d4e8-43a5-bd39-dbbc5f994114

**Comment by Scarlaid** [comment]
I was on 1.19.4

**Comment by Scarlaid** [comment]
It seems to be happening on 1.19.4 only, went ahead and tried on 1.20.1 and works fine

little edit: confirmed to be happening on 1.19.4, even pressing F5 crashes the game with MCC

**Comment by 70CentsApple** [comment]
Okay, it should work fine now. Re-download it [through Github](https://github.com/70CentsApple/modify-camera-collision/releases/download/v1.0.0/modify-camera-collision-1.0.0+1.19.4.jar) or [through Modrinth](https://modrinth.com/mod/modify-camera-collision/version/3yeJvx5m) .

If you find other incompatibilities or crashes, feel free to open an issue here.
