### ISSUE TITLE
incompatibility with shoulder surfing

### ISSUE THREAD

**Issue by Trickster-4** [70CentsApple/modify-camera-collision#2]
this mods adds one extra camera on F5. because of that the mod doesn't recognizes it and the modifications I make on the mod doesn't affects the forth one.

**Comment by 70CentsApple** [comment]
Sorry for the delay. I have already made an upstream fix and it is ~~waiting to be~~ merged.
See it here: https://github.com/Exopandora/ShoulderSurfing/pull/130.

**Comment by 70CentsApple** [comment]
Since it has been merged for a while, I will just close this issue if there is no other problem.
